// Knowledge base loader. Source of truth: /kb/*.md + /kb/_meta.json (English).
// Per-language overrides live at /kb/{lang}/*.md + /kb/{lang}/_meta.json
// and are generated by scripts/translate-kb-bulk.ts.
import metaRaw from "/kb/_meta.json?raw";
import type { LanguageCode } from "@/contexts/LanguageContext";

export type TopicMeta = {
  slug: string;
  title: string;
  category: string;
  /** Section name as cited in chat replies, e.g. "Burns" or "Anaphylaxis". */
  section: string;
  summary: string;
  keywords: string[];
  related: string[];
};

type LangMeta = {
  language: string;
  categories: Record<string, string>;
  topics: Array<{ slug: string; title: string; summary: string }>;
};

// English bodies
const enBodies = import.meta.glob("/kb/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

// All translated bodies, keyed by `/kb/{lang}/{slug}.md`
const langBodies = import.meta.glob("/kb/*/*.md", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

// Per-language meta files
const langMetaRaw = import.meta.glob("/kb/*/_meta.json", {
  query: "?raw",
  import: "default",
  eager: true,
}) as Record<string, string>;

const langMetaByCode: Record<string, LangMeta> = {};
for (const [path, raw] of Object.entries(langMetaRaw)) {
  const m = path.match(/\/kb\/([^/]+)\/_meta\.json$/);
  if (m) {
    try {
      langMetaByCode[m[1]] = JSON.parse(raw);
    } catch {
      /* ignore malformed */
    }
  }
}

const enTopics: TopicMeta[] = (JSON.parse(metaRaw) as TopicMeta[])
  .slice()
  .sort((a, b) => a.title.localeCompare(b.title));

export const topics: TopicMeta[] = enTopics;

export const categories: string[] = Array.from(
  new Set(topics.map((t) => t.category)),
).sort();

/** Topics for a given language (uses translated title/summary when available). */
export function topicsFor(lang: LanguageCode = "en"): TopicMeta[] {
  if (lang === "en") return enTopics;
  const lm = langMetaByCode[lang];
  if (!lm) return enTopics;
  const trBySlug = Object.fromEntries(lm.topics.map((t) => [t.slug, t]));
  const catMap = lm.categories || {};
  return enTopics
    .map((t) => {
      const tr = trBySlug[t.slug];
      return {
        ...t,
        title: tr?.title || t.title,
        summary: tr?.summary || t.summary,
        category: catMap[t.category] || t.category,
      };
    })
    .sort((a, b) => a.title.localeCompare(b.title));
}

export function getTopic(slug: string, lang: LanguageCode = "en"): TopicMeta | undefined {
  return topicsFor(lang).find((t) => t.slug === slug);
}

export function getBody(slug: string, lang: LanguageCode = "en"): string {
  if (lang !== "en") {
    const k = `/kb/${lang}/${slug}.md`;
    if (langBodies[k]) return langBodies[k];
  }
  return enBodies[`/kb/${slug}.md`] ?? "";
}

export function topicsByCategory(lang: LanguageCode = "en"): Record<string, TopicMeta[]> {
  const out: Record<string, TopicMeta[]> = {};
  for (const t of topicsFor(lang)) {
    (out[t.category] ||= []).push(t);
  }
  return out;
}

/** Match a free-form section name to a KB slug (uses English metadata). */
export function findTopicBySection(name: string): TopicMeta | undefined {
  const n = name.trim().toLowerCase().replace(/\([^)]*\)/g, "").trim();
  if (!n) return undefined;
  const exact = enTopics.find((t) => t.section.toLowerCase() === n);
  if (exact) return exact;
  const byTitle = enTopics.find((t) => t.title.toLowerCase() === n);
  if (byTitle) return byTitle;
  const sub = enTopics.find(
    (t) =>
      n.includes(t.section.toLowerCase()) ||
      t.section.toLowerCase().includes(n) ||
      t.title.toLowerCase().includes(n),
  );
  if (sub) return sub;
  return enTopics.find((t) =>
    t.keywords.some((k) => n.includes(k.toLowerCase())),
  );
}
